name: dinogrow
description: 2D blockchain game about growing dinosaurs.
version: 1.0.3+6

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  solana: ^0.29.1
  bip39: ^1.0.6
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.1.0
  flame: 1.8.2
  flame_forge2d: 0.14.1+1
  flutter_joystick: ^0.0.3
  url_launcher: ^6.1.14
  qr_flutter: ^4.1.0
  http: ^0.13.6
  borsh: ^0.3.1+2
  borsh_annotation: ^0.3.1+3
  solana_web3: ^0.0.8
  solana_common: ^0.0.5
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/up/
    - assets/images/up/green/run/
    - assets/images/up/green/walk/
    - assets/images/up/green/dead/
    - assets/images/up/green/idle/
    - assets/images/up/green/jump/
    - assets/images/up/maps/01/
    - assets/images/dinopad/
    - assets/images/ui/
    - assets/images/icons/
    - .env
