name: dinogrow
description: 2D blockchain game about growing dinosaurs.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  solana: ^0.29.1
  bip39: ^1.0.6
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.1.0
  flame: ^1.8.2
  flame_forge2d: ^0.14.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.jpeg
  - assets/images/up/green/run/
  - assets/images/up/green/walk/
  - .env